from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime


def generate_report(
    filename,
    url,
    trust_score,
    ai_result,
    ssl_status,
    https_status,
    blacklist_status
):
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(filename)

    story = []

    # Title
    story.append(Paragraph("<b>TrustLens AI</b>", styles["Title"]))
    story.append(Paragraph("Website Trust Analysis Report", styles["Heading2"]))
    story.append(Spacer(1, 20))

    # Scan Time
    story.append(
        Paragraph(
            f"<b>Scan Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 15))

    # Report Table
    data = [
        ["Parameter", "Result"],
        ["Website URL", url],
        ["Trust Score", f"{trust_score}/100"],
        ["AI Verdict", ai_result],
        ["SSL Certificate", "Valid" if ssl_status else "Invalid"],
        ["HTTPS", "Enabled" if https_status else "Disabled"],
        ["Blacklist", "Listed" if blacklist_status else "Not Listed"],
    ]

    table = Table(data, colWidths=[180, 280])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))

    story.append(table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Generated by TrustLens AI - AI Website Trust Analyzer</b>",
            styles["Italic"],
        )
    )

    doc.build(story)